In [2]:
import pandas as pd

In [20]:
import pandas as pd

pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", None)

In [3]:
df = pd.read_csv('./datasets/zerve_events.csv')

C:\Users\anxpr\AppData\Local\Temp\ipykernel_25508\3205404977.py:1: DtypeWarning: Columns (0: person_properties.cloudProvider, 1: person_properties.purpose, 2: person_properties.role, 3: person_properties.source, 4: person_properties.work_type, 5: properties.$ai_model, 6: properties.$ai_provider, 7: properties.$ai_tools_called, 8: properties.block_type, 9: properties.block_types, 10: properties.button_name, 11: properties.connectionType, 12: properties.feature_tag, 13: properties.file_extension, 14: properties.file_type, 15: properties.link_name, 16: properties.offer_declined, 17: properties.role, 18: properties.share_platform, 19: properties.skipped, 20: properties.subscription_type, 21: properties.utm_campaign, 22: properties.utm_content, 23: properties.utm_medium, 24: properties.utm_source, 25: properties.utm_term, 26: properties.workspace_id) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('./datasets/zerve_events.csv')

In [4]:
df.shape

(3509628, 83)

In [5]:
df.columns

Index(['person_id', 'timestamp', 'event', 'person_properties.cloudProvider',
       'person_properties.purpose', 'person_properties.role',
       'person_properties.source', 'person_properties.work_type',
       'properties.$browser', 'properties.$browser_language',
       'properties.$browser_version', 'properties.$device',
       'properties.$device_type', 'properties.$os', 'properties.$os_version',
       'properties.$geoip_continent_name', 'properties.$geoip_country_name',
       'properties.$geoip_time_zone', 'properties.$screen_height',
       'properties.$screen_width', 'properties.$ai_input_tokens',
       'properties.$ai_latency', 'properties.$ai_model',
       'properties.$ai_output_tokens', 'properties.$ai_provider',
       'properties.$ai_tool_call_count', 'properties.$ai_tools_called',
       'properties.amount', 'properties.block_type', 'properties.block_types',
       'properties.button_name', 'properties.canvas_id',
       'properties.connectionType', 'properties.credit_amount',
       'properties.credits_awarded', 'properties.credits_received',
       'properties.credits_remaining', 'properties.credits_used',
       'properties.current_canvases_count', 'properties.feature_tag',
       'properties.file_extension', 'properties.file_type',
       'properties.link_name', 'properties.number_of_apps',
       'properties.number_of_blocks', 'properties.number_of_canvases',
       'properties.number_of_files', 'properties.number_of_seats',
       'properties.offer_declined', 'properties.pending_tasks_count',
       'properties.rating', 'properties.requirements_status',
       'properties.role', 'properties.share_platform', 'properties.skipped',
       'properties.source', 'properties.subscription_type',
       'properties.tool_name', 'properties.total_addon_credits',
       'properties.total_credits', 'properties.utm_campaign',
       'properties.utm_content', 'properties.utm_medium',
       'properties.utm_source', 'properties.utm_term',
       'properties.workspace_id', 'properties.$event_type',
       'properties.$lib_rate_limit_remaining_tokens',
       'properties.$prev_pageview_duration',
       'properties.$prev_pageview_last_content',
       'properties.$prev_pageview_last_content_percentage',
       'properties.$prev_pageview_last_scroll',
       'properties.$prev_pageview_last_scroll_percentage',
       'properties.$prev_pageview_max_content',
       'properties.$prev_pageview_max_content_percentage',
       'properties.$prev_pageview_max_scroll',
       'properties.$prev_pageview_max_scroll_percentage',
       'properties.$search_engine', 'properties.$web_vitals_CLS_value',
       'properties.$web_vitals_FCP_value', 'properties.$web_vitals_INP_value',
       'properties.$web_vitals_LCP_value',
       'properties.$web_vitals_enabled_server_side'],
      dtype='str')

counting nulls under each feature

In [16]:
df_count_nulls = {}

for column in df.columns:
    df_count_nulls[column] = df[column].isnull().sum()

summary_nulls = pd.DataFrame(df_count_nulls, index=["count_nulls"]).T

In [42]:
summary_nulls.head(10)

                                 count_nulls
person_id                                  0
timestamp                                  0
event                                      0
person_properties.cloudProvider      3507489
person_properties.purpose            1497759
person_properties.role               1264978
person_properties.source             1682311
person_properties.work_type          1571686
properties.$browser                  2535841
properties.$browser_language         2535841

In [40]:
print(summary_nulls["count_nulls"].unique())
print(f"number of col with nulls: {len(summary_nulls['count_nulls'].unique())}")

[      0 3507489 1497759 1264978 1682311 1571686 2535841 2538924 3422981
  549822  657429 1986064 2959810 3296653 3509554 3493063 3503970 3509075
 3306963 3509514 2575178 3507626 3508948 3507488 3047198 3509500 3509624
 3507120 3508755 3505973 3509626 3501205 3508900 3504162 3509584 3509621
 3509595 3509622 3509531 3509586 3509617 3505914 3480696 3145156 3507910
 3484576 3496749 3500737 3477472 3508461 3509623 3499692 3477576 3477639
 3069865 3470938 3473254 3454679 3474184 2775704]
number of col with nulls: 60

In [34]:
sum_null_col_count = summary_nulls.groupby("count_nulls").size().reset_index(name="num_columns").sort_values(by="num_columns", ascending=False)
sum_null_col_count[sum_null_col_count["num_columns"] > 1]

    count_nulls  num_columns
25      3477639            8
8       2535841            6
12      2959810            5
0             0            3
7       1986064            3
38      3507488            2
16      3296653            2
58      3509624            2

In [43]:
sum_null_col_count = (
    summary_nulls
    .reset_index(names="column_name")
    .groupby("count_nulls")
    .agg(
        num_columns=("column_name", "size"),
        column_names=("column_name", list)
    )
    .reset_index()
    .sort_values(by="num_columns", ascending=False)
)

sum_null_col_count[sum_null_col_count["num_columns"] > 1]

,count_nulls,num_columns,column_names
25,3477639,8,"[properties.$prev_pageview_last_content, properties.$prev_pageview_last_content_percentage, properties.$prev_pageview_last_scroll, properties.$prev_pageview_last_scroll_percentage, properties.$prev_pageview_max_content, properties.$prev_pageview_max_content_percentage, properties.$prev_pageview_max_scroll, properties.$prev_pageview_max_scroll_percentage]"
8,2535841,6,"[properties.$browser, properties.$browser_language, properties.$device_type, properties.$screen_height, properties.$screen_width, properties.$lib_rate_limit_remaining_tokens]"
12,2959810,5,"[properties.$ai_input_tokens, properties.$ai_latency, properties.$ai_model, properties.$ai_output_tokens, properties.$ai_provider]"
0,0,3,"[person_id, timestamp, event]"
7,1986064,3,"[properties.$geoip_continent_name, properties.$geoip_country_name, properties.$geoip_time_zone]"
38,3507488,2,"[properties.credits_remaining, properties.total_credits]"
16,3296653,2,"[properties.$ai_tool_call_count, properties.$ai_tools_called]"
58,3509624,2,"[properties.feature_tag, properties.subscription_type]"